config/routes.rb
Rails.application.routes.draw do
  # httpﾘｸｴｽﾄ  urlﾊﾟｽ  ｺﾝﾄﾛｰﾗｰ名#ｱｸｼｮﾝ名
  resources :books
  # resources付けることによって、下記ルーティングが自動で作成され、
  # books controllerに対応付られる。下記ルーティングは記載不要。

  # get 'books' => 'books#index'
  # get 'books/:id' => 'books#show'
  # get 'books/:id/edit' => 'books#edit'
  # post 'books' => 'books#create'
  # patch 'books/:id' => 'books#update'
  # delete 'books/:id' => 'books#destroy'

  root to: 'homes#top'
  # root：ｱｸｾｽして一番最初のｺﾝﾄﾛｰﾗへの指示,rootは主にtoppageなどに用いられます。



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    # ここからはmodelとの連携
    # ﾓﾃﾞﾙ名.ﾒｿｯﾄﾞ Book.all.  @instance = model.method
    # all:dbの全てのデータを取得
    # find:db内の、1つのデータを取得
    # new:データの新規作成を生成する
    # save:dbにデータを保存する

    # ここからはviewとの連携 controllerからviewへ
    # modelからのﾃﾞｰﾀをｲﾝｽﾀﾝｽ変数に代入する。これでviewでﾃﾞｰﾀ使える
    # @books = Book.all @instance = model.method

  end

  def create
    @book = Book.new(book_params)
    if @book.save
     redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @books = Book.all
      render 'books/index'
    end
  end

  def update
    @book = Book.find(params[:id])
    # @instance = model.find(params[:カラム名])
    # @instance = model.find(params[:id])
    # paramsはrailsで送られてきた値を受け取るmethod
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice: "Book was successfully updated."
    else
      render 'books/edit'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

   private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<%= stylesheet_link_tag "books", :media => "all" %>
<h2>Editiong Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book,url:'/books/' + @book.id.to_s,method: :patch, local:true do |f| %>
  <p class="edit_html">Title</p>
  <%= f.text_field :title %>

  <p class="edit_html">Body</p>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' , :class => "btn" %>
<% end %>

<span><%= link_to 'Show','/books/' + @book.id.to_s %></span>
<span>|</span>
<span><%= link_to 'Back','/books' %></span>

app/views/books/index.html.erb
<%= stylesheet_link_tag "books", :media => "all" %>
<h1 class="index_html">Books</h1>
<table class= "index_html">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |b| %>
    <tr>
      <td><%= b.title %></td>
      
      <td><%= b.body %></td>
      <td><%= link_to 'Show','/books/'+ b.id.to_s %></td>
      <td><%= link_to 'Edit','/books/'+ b.id.to_s + '/edit' %></td>
      <td><%= link_to 'Destroy','/books/'+ b.id.to_s, method: :delete, "data-confirm" => "Are you sure" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class ="index_html_newbook">
<h2>New Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book,url:'/books',method: :post, local:true do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>

  <p>Body</p>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Create Book' %>
<% end %>
</div>

app/views/books/show.html.erb
<%= stylesheet_link_tag "books", :media => "all" %>
<p class = "show_html_flash"><%= flash[:notice] %></p><br>
<span class="show_html"><strong>Title:</strong><%= @book.title %></span><br>
<span class="show_html"><strong>Body:</strong><%= @book.body %></span><br>

<span><%= link_to 'Edit','/books/'+ @book.id.to_s + '/edit' %></span>
<span>|</span>
<span><%= link_to 'Back','/books' %></span>

app/views/homes/top.html.erb
<%= stylesheet_link_tag "homes", :media => "all" %>

<h1>ようこそBookersへ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<p><%= link_to 'start',books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>